app:
    detectedTagMap:
        unwanted:
            - monocolor
    tags:
        nude: copyToAnomaly
        monocolor: moveToAnomaly
    googleTestDevicesIpRegex: (^108\.177\.6\.[0-9]+$)|(^104\.196\.[0-9]+\.[0-9]+$)
    log:
        folder: logs
        file: rando-exchanger.log
        handleException: true
        level:
            console: trace
            file: info
exch:
    fetchRandosNumber: 1000
firebase:
    key: STUB_SERVER_API_KEY
    timeout: 3000
    parallelMessagesLimit: 2
db:
    url: mongodb://localhost/rando
