app:
    tags:
        nude: copyToAnomaly
        monocolor: moveToAnomaly
    googleTestDevicesIpRegex: (^108\.177\.6\.[0-9]$)|(^108\.177\.6\.1[0-9]$)|(^108\.177\.6\.2[0-4]$)|(^104\.196\.0\.[0-9]$)|(^104\.196\.0\.1[0-6]$)
    log:
        folder: logs
        file: rando-exchanger.log
        handleException: true
        level:
            console: trace
            file: info
exch:
    fetchRandosNumber: 1000
firebase:
    key: STUB_SERVER_API_KEY
db:
    url: mongodb://localhost/rando
