app:
    log:
        folder: logs
        file: rando-exchanger.log
        handleException: true
        level:
            console: trace
            file: info
exch:
    fetchRandosNumber: 1000
firebase:
    key: STUB_SERVER_API_KEY
db:
    url: mongodb://localhost/rando
